My first pull request
chidiebereojingwa/Hello_Microverse pull request #1
Opened 2021-08-10 21:26 UTC by chidiebereojingwa

2021-08-10 22:43 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @chidiebereojingwa , You did a great job so far 👏🏼 👏🏼 

- Good job on using the microverse readme template.
- the commits are descriptive.
- Gitflow is correctly used.

However, here are some points that you need to work on to get your project approved.

## Required changes :

Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-10 22:43 UTC, safafa commented on README.md
> +![screenshot](./app_screenshot.png)
- [ ] I think it will be better if you use the project's screenshot. It will look professional. You can also add a small description of the project

2021-08-10 22:43 UTC, safafa commented on README.md
> +
- [ ] You can delete the sections that you don't need instead of leaving them empty. In the setup section add information about how to get a local copy of the the project.

2021-08-10 22:43 UTC, safafa commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/chidiebereojingwa)
- [ ] I think it will look better if you remove this extra section

2021-08-10 22:43 UTC, safafa commented on test.md
> +This file should be ignored by git
- [ ] This file should be ignored by git , I checked your files the .gitignore file doesn't have .txt extension Kindly fix the issue. the file listing test.md file and node_modules directory (as it can be added by accident while setting up linters).

2021-08-11 20:35 UTC, barackm requested changes
Hi @chidiebereojingwa , 👋 

Great work on making the changes requested by a previous reviewer 👏 👏👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 😉  😉 

 # STATUS: Required Changes ♻️

- [x] As requested by the previous reviewer the pull request should have a descriptive summary describing the changes you have made, please let us fix this issue. if you need a refresher on how to add a pull request summary you can open [this link](https://maddevs.io/blog/how-to-make-a-proper-description-for-a-pull-request/)

### _Check the comments under the review._ 👇 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 20:35 UTC, barackm commented on README.md
> +clone to you local machine
- [ ] [OPTIONAL] Great job on adding the setup section to your README, but it could be nicer if you give more details on how to clone the repository so that non-technical people can get an idea on how to do it

2021-08-11 20:35 UTC, barackm commented on README.md
> +# Project Name
- [ ] [OPTIONAL] It could be nicer if you replace the Project Name with the actual name of your project instead of adding it below the project name.

2021-08-11 22:12 UTC, barackm approved these changes
Hi @chidiebereojingwa, 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] I can see in your commits that you have deleted the `package-lock.json`, you do not need to delete that file because it keeps track of the exact versions of packages you install in your project. You can also keep the package.json because it also contains the packages you have installed. this will make it easier for someone cloning your project to get access to those packages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 22:22 UTC, merged